name: "Java Build Action"
description: "Compile and run Java Program"

inputs:
  file-name:
    description: "Java file name"
    required: true
    default: "CalculatorTest"

runs:
  using: "composite"
  steps:
    - name: Compile Java Program
      run: java -cp . ${{ inputs.file-name }}.java
      shell: bash

    - name: Run Java Program
      run: java -cp . ${{ inputs.file-name }}
      shell: bash


